export default Object.freeze({

    ENV: process.env.MIX_APP_ENV,
    STRIPE_KEY: process.env.MIX_STRIPE_KEY,
    VISIBILITY_PUBLIC : 1,
    VISIBILITY_PRIVATE: 0,
    //Experience Statuses
    EXPERIENCE_TYPE_JOURNEY: "journey",
    EXPERIENCE_TYPE_ADVENTURE: "adventure",
    EXPERIENCE_STATUS_INACTIVE: 0,
    EXPERIENCE_STATUS_PUBLISHED: 1,
    EXPERIENCE_STATUS_DRAFT: 2,
    EXPERIENCE_AUTHOR_DEFAULT: 1,

    //Enrollment Statuses
    ENROLLMENT_STATUS_ABANDONED: 0,
    ENROLLMENT_STATUS_ENROLLED: 1,
    ENROLLMENT_STATUS_FINISHED: 2,
    ENROLLMENT_STATUS_SUSPENDED: 3,
    ENROLLMENT_STATUS_EXPIRED: 4,
    ENROLLMENT_STATUS_EXPULSED: 5,
    ENROLLMENT_STATUS_STARTED: 6,
    ENROLLMENT_STATUS_IN_PROGRESS: 7,

    //Session Statuses
    SESSION_STATUS_BLOCKED: 0,
    SESSION_STATUS_AVAILABLE: 1,
    SESSION_STATUS_IN_PROGRESS: 2,
    SESSION_STATUS_FINISHED: 3,
    SESSION_STATUS_RETRY: 4,
    SESSION_STATUS_FINISHED_PENDING_ANSWERS: 5,

    //Session tracking types
    TRACKING_TYPE_XAPI: 'xapi',
    TRACKING_TYPE_VIDEO: 'video_event',

    //XAPI Events
    XAPI_VERB_ATTEMPTED: 'attempted',
    XAPI_VERB_COMPLETED: 'completed',
    XAPI_VERB_ANSWERED: 'answered',
    XAPI_VERB_INTERACTED: 'interacted',

    EVENT_VIDEO_STARTED: 'video_started',
    EVENT_VIDEO_SEEKING: 'video_seeking',
    EVENT_VIDEO_PAUSED: 'video_paused',
    EVENT_VIDEO_FINISHED: 'video_finished',

    BUY_LIMIT: 100000
});
