export default {
    'Home': () => import ('./home/Home'),
    'recovery-password': () => import('../website/reset-password/RecoveryPassword'),
    'reset-password': () => import('../website/reset-password/ResetPassword'),

    'apithy-owner-menu': () => import ('./OwnerMenu.vue'),
    'apithy-owner-left-menu': () => import ('./OwnerLeftMenu'),
    'apithy-owner-tabs-menu': () => import ('./OwnerTabsMenu'),
    'apithy-plattform-menu': () => import ('./PlattformMenu'),
    'apithy-platform-nav': () => import ('./PlatformNav'),

    'apithy-partner-nav': () => import ('./partner/PartnerNav'),
    'apithy-profile': () => import ('../Profile'),
    'apithy-profile-form': () => import ('../ProfileForm'),
    'apithy-select': () => import (ApithySelect),
    'apithy-register': () => import ('../Register'),
    'apithy-security': () => import ('../Security'),
    'apithy-image-upload': () => import ('../ImageUpload'),
    'apithy-student-analytics': () => import ('./StudentAnalytics'),
    'apithy-user-payment-information': () => import ('../PaymentInformation'),
    'apithy-user-payment-information-form': () => import ('../PaymentInformationForm'),
    'apithy-user-payment-information-form-edit': () => import ('../PaymentInformationFormEdit'),
    'apithy-user-transactions': () => import ('../Transactions'),
    'apithy-resource-paginator': () => import ('../ResourcePagination'),
    'apithy-cart-checkout': () => import ('./checkout/CartCheckout'),
    'apithy-chart': () => import ('../admin/ApithyChart'),
    'apithy-buy-licences': () => import ('./ExperienceLicenseAssignation'),
    'apithy-flash-message': () => import ('../FlashMessage'),

    'apithy-marketplace': () => import ('./marketplace/Principal'),
    'apithy-experience-list': () => import ('./ExperienceList'),
    'apithy-experience-carousel': () => import ('./ExperienceCarousel'),
    'apithy-experience-preview': () => import ('./ExperiencePreview'),
    'apithy-experience-public-preview': () => import ('./ExperiencePublicPreview'),
    'apithy-experience-viewer': () => import ('./ExperienceViewer'),
    'apithy-experience-public-viewer': () => import ('./ExperiencePublicViewer'),
    'apithy-experience-player': () => import ('./experience_player/ExperiencePlayer'),
    'apithy-public-experience-player': () => import ('./experience_player/PublicExperiencePlayer'),
    'apithy-experience-rating': () => import ('./ExperienceRating'),
    'apithy-experience-licenses': () => import ('../admin/experiences/licenses/ExperienceLicenses'),
    'apithy-experience-editor': () => import ('../admin/experiences/editor/ExperienceEditor'),
    'apithy-experience-container': () => import ('./experience_render/Container'),


    'apithy-areaposition-form': () => import ('../admin/company-forms/AreasPositionsForm'),
    'apithy-ability-list': () => import ('../admin/abilities/AbilityList'),
    'apithy-tag-list': () => import ('../admin/tags/TagList'),

    'apithy-table': () => import ('../admin/ApithyTable'),

    'apithy-invitations': () => import ('../admin/Invitations.vue'),
    'apithy-users-filter': () => import ('../admin/users/UsersFilter'),
    'apithy-users-list': () => import ('../admin/users/UserList'),
    'apithy-users-form': () => import ('../admin/users/UserForm'),
    'apithy-users-edit': () => import ('../admin/users/UsersEdit'),
    'apithy-users-import': () => import ('../admin/users/UsersImport'),
    'apithy-users-invitations': () => import ('../admin/users/UsersInvitations'),
    'apithy-users-owner': () => import ('./users/OwnerUsersModule.vue'),
    'apithy-users-create-import': () => import ('./users/OwnerUsersCreateImport.vue'),

    'apithy-companies-list': () => import ('../admin/company/CompanyList'),
    'apithy-companies-filter': () => import ('../admin/company/CompanyFilter'),
    'apithy-companies-form': () => import ('../admin/company/CompanyForm'),
    'apithy-companies-edit': () => import ('../admin/company/CompanyEdit'),
    'apithy-company-menu': () => import ('../admin/company/CompanyMenu'),
    'apithy-budget-list': () => import ('../admin/company/CompanyBudgetList'),
    'apithy-companies-budget-form': () => import ('../admin/company/CompanyBudgetForm'),

    'apithy-cart-notification': () => import ('./CartNotify'),

    'apithy-menu-dashboard': () => import ('../admin/dashboard/Menu'),
    'apithy-admin-general-dashboard': () => import ('../admin/dashboard/admin/AdminGeneralDashboard'),
    'apithy-admin-summary-dashboard': () => import ('../admin/dashboard/admin/AdminSummaryDashboard'),
    'apithy-admin-journeys-dashboard': () => import ('../admin/dashboard/admin/AdminJourneysDashboard'),
    'apithy-admin-experiences-dashboard': () => import ('../admin/dashboard/admin/AdminExperienceDashboard'),
    'apithy-admin-users-dashboard': () => import ('../admin/dashboard/admin/AdminStatsByUser'),
    'apithy-reports-dashboard': () => import('../admin/dashboard/admin/reports/Reports'),
    'apithy-admin-detail-stacked': () => import ("../admin/dashboard/detailed/DetailedStackedGraph"),
    'apithy-admin-detail-average': () => import ("../admin/dashboard/detailed/DetailedAverageGraph"),
    'apithy-admin-detail-licenses': () => import ("../admin/dashboard/detailed/DetailedLicensesGraph"),
    'apithy-admin-detail-popularity': () => import ("../admin/dashboard/detailed/DetailedPopularityGraph"),
    'apithy-admin-detail-califications': () => import ("../admin/dashboard/detailed/DetailedCalificationsGraph"),

    'apithy-partner-dashboard': () => import ('./partner/Dashboard'),
    'apithy-partner-experiences': () => import ('./partner/Experiences'),
    'apithy-partner-ingress': () => import ('./partner/Ingress'),
    'apithy-partner-conciliation': () => import ('./partner/Conciliation'),
    'apithy-getting-started': () => import ("./getting_started/GettingStarted"),
    'apithy-getting-started-cards': () => import ("./getting_started_card/GettingStarted"),
    'apithy-company-user-login': () => import ("../website/CompanyUserLogin"),
    'apithy-licenses-list': () => import ('../admin/experiences/licenses/LicensesList'),
    'apithy-login': () => import ("../website/ApithyLogin"),
    'apithy-admin-taxonomy': () => import ("./taxonomy/ApithyTaxonomy"),

    'apithy-demo-invitations': () => import ('../admin/users/DemoInvitations'),
    'apithy-footer': () => import ("./ApithyFooter"),

    'activity-evaluations': () => import ("../website/temporalComponents/ActivityEvaluation"),
    'apithy-evaluation': () => import ('./evaluations/Evaluation'),
    'experience-render': () => import ( "../admin/experiences/editor/components/ExperienceRender"),

  "apithy-set-password": () => import("./password/ApithySetPassword")
};
