<?php

namespace Apithy\Services\Eva;

use Apithy\EvaluationUser;
use Apithy\Question;
use Apithy\Services\ReactiveService;

class ClickAndDropReactive extends Reactive
{
    public function checkAnswers(Question $question, array &$userAnswers): void
    {
        //parent::checkAnswers($question, $userAnswers); // TODO: Change the autogenerated stub
        //$this->filterUserAnswers($question, $userAnswers);
        $this->completeAnswers($question, $userAnswers);
    }

    private function filterUserAnswers(Question $question, array &$userAnswers) : void
    {
        foreach ($question->answers as $answer) {
            foreach ($userAnswers as &$ua) {
                if ($answer->id == $ua['answer_id']) {
                    if ($answer->is_correct) {
                        $ua['is_correct'] = true;
                    }
                }
            }
        }
    }

    private function completeAnswers(Question $question, array &$userAnswers) : void
    {
        $original = collect($userAnswers)
            ->whereIn('answer_id', $question->answers->pluck('id'));
        $success = true;
        $original->each(function (&$answer, $key) use ($question, &$success, &$userAnswers) {
            $configurations = collect($answer['configurations']);
            $dbAnswer = $question->answers()->where('id', $answer['answer_id'])->first();
            $related = collect($dbAnswer->configurations)->get('related_options');
            $related = collect($related)->sortBy('title');
            $selected = $configurations->get('selected_options');
            $selected = collect($selected)->sortBy('title');

            if (count($related) !== count($selected)) {
                return $success = false;
            }

            $ser1 = serialize($related->values());
            $ser2 = serialize($selected->values());

            $isEquals = strcasecmp($ser1, $ser2);

            if ($isEquals !== 0) {
                return $success = false;
            }

            $userAnswers[$key]['is_correct'] = true;
        });
        $question->valid = $success;
    }
}
